# This YAML file only suit for python package: dynamic-yaml

# Directory settings 
DIRS: 
    DATASET_DIR: "/workspace/multivariate-correlation-anomaly-detection/dataset"
    PIPELINE_DATA_DIR: "{DIRS.DATASET_DIR}/pipeline_dataset"

RANDOM_SEEDS:
    DEFAUTL_SEED: &default_seed 10
    SEED_1: 20

# loading & implement setting
DATASETS:
    SP500_20082017:
        FILE_PATH: "{DIRS.DATASET_DIR}/is_pre_data/sp500_hold_20082017_adj_close-pre.csv"
        ALL_SET: &sp500_20082017_all_set ['A', 'AAL', 'AAP', 'AAPL', 'ABC', 'ABT', 'ACN', 'ADBE', 'ADI', 'ADM', 'ADP', 'ADSK', 'AEE', 'AEP', 'AES', 'AET', 'AFL', 'AIG', 'AIV', 'AIZ', 'AJG', 'AKAM', 'ALB', 'ALGN', 'ALK', 'ALL', 'AMAT', 'AMD', 'AME', 'AMG', 'AMGN', 'AMP', 'AMT', 'AMZN', 'ANSS', 'AON', 'AOS', 'APA', 'APD', 'APH', 'ARE', 'ATVI', 'AVB', 'AVY', 'AXP', 'AYI', 'AZO', 'BA', 'BAC', 'BAX', 'BBY', 'BDX', 'BEN', 'BIIB', 'BK', 'BLK', 'BMY', 'BRK', 'BSX', 'BWA', 'BXP', 'C', 'CA', 'CAG', 'CAH', 'CAT', 'CB', 'CCI', 'CCL', 'CDNS', 'CF', 'CHD', 'CHRW', 'CI', 'CINF', 'CL', 'CLX', 'CMA', 'CMCSA', 'CME', 'CMG', 'CMI', 'CMS', 'CNC', 'CNP', 'COF', 'COO', 'COP', 'COST', 'CPB', 'CRM', 'CSCO', 'CSX', 'CTAS', 'CTSH', 'CVS', 'CVX', 'D', 'DAL', 'DE', 'DFS', 'DGX', 'DHI', 'DHR', 'DIS', 'DISH', 'DLR', 'DLTR', 'DOV', 'DRI', 'DTE', 'DUK', 'DVA', 'DVN', 'EA', 'EBAY', 'ECL', 'ED', 'EFX', 'EIX', 'EL', 'EMN', 'EMR', 'EOG', 'EQIX', 'EQR', 'EQT', 'ES', 'ESRX', 'ESS', 'ETN', 'ETR', 'EW', 'EXC', 'EXPD', 'EXPE', 'EXR', 'F', 'FAST', 'FCX', 'FDX', 'FE', 'FFIV', 'FIS', 'FITB', 'FL', 'FLR', 'FLS', 'FMC', 'FRT', 'FTI', 'GD', 'GE', 'GILD', 'GIS', 'GLW', 'GOOGL', 'GPC', 'GPN', 'GPS', 'GRMN', 'GS', 'GT', 'GWW', 'HAL', 'HAS', 'HBAN', 'HBI', 'HD', 'HES', 'HIG', 'HOG', 'HOLX', 'HON', 'HP', 'HPQ', 'HRB', 'HRL', 'HSIC', 'HST', 'HSY', 'HUM', 'IBM', 'ICE', 'IDXX', 'IFF', 'ILMN', 'INCY', 'INTC', 'INTU', 'IP', 'IPG', 'IPGP', 'IRM', 'ISRG', 'IT', 'ITW', 'IVZ', 'JBHT', 'JCI', 'JNJ', 'JNPR', 'JPM', 'JWN', 'K', 'KEY', 'KIM', 'KLAC', 'KMB', 'KMX', 'KO', 'KR', 'KSS', 'L', 'LEG', 'LEN', 'LH', 'LKQ', 'LLY', 'LMT', 'LNC', 'LNT', 'LOW', 'LRCX', 'LUV', 'M', 'MA', 'MAA', 'MAC', 'MAR', 'MAS', 'MAT', 'MCD', 'MCHP', 'MCK', 'MCO', 'MDLZ', 'MDT', 'MET', 'MGM', 'MHK', 'MKC', 'MLM', 'MMC', 'MNST', 'MO', 'MOS', 'MRK', 'MRO', 'MS', 'MSCI', 'MSFT', 'MSI', 'MTB', 'MTD', 'MU', 'NDAQ', 'NEE', 'NEM', 'NFLX', 'NFX', 'NI', 'NKE', 'NKTR', 'NOC', 'NOV', 'NRG', 'NSC', 'NTAP', 'NTRS', 'NUE', 'NVDA', 'NWL', 'O', 'OKE', 'OMC', 'ORCL', 'ORLY', 'OXY', 'PAYX', 'PCAR', 'PCG', 'PEG', 'PEP', 'PFE', 'PFG', 'PG', 'PGR', 'PH', 'PHM', 'PKG', 'PLD', 'PNC', 'PNR', 'PNW', 'PPL', 'PRGO', 'PRU', 'PSA', 'PVH', 'PWR', 'PXD', 'QCOM', 'RCL', 'REG', 'REGN', 'RF', 'RHI', 'RJF', 'RL', 'RMD', 'ROK', 'ROP', 'ROST', 'RRC', 'RSG', 'SBAC', 'SBUX', 'SCHW', 'SEE', 'SHW', 'SJM', 'SLB', 'SLG', 'SNA', 'SNPS', 'SO', 'SPG', 'SRCL', 'SRE', 'STT', 'STX', 'STZ', 'SWK', 'SWKS', 'SYK', 'SYY', 'T', 'TAP', 'TDG', 'TEL', 'TGT', 'TJX', 'TMO', 'TROW', 'TSCO', 'TSN', 'TTWO', 'TWX', 'TXN', 'TXT', 'UAA', 'UAL', 'UDR', 'UHS', 'ULTA', 'UNH', 'UNM', 'UNP', 'UPS', 'URI', 'USB', 'VFC', 'VLO', 'VMC', 'VNO', 'VRSN', 'VRTX', 'VTR', 'VZ', 'WAT', 'WBA', 'WDC', 'WEC', 'WFC', 'WHR', 'WM', 'WMB', 'WMT', 'WU', 'WY', 'WYNN', 'XEL', 'XOM', 'XRAY', 'XRX', 'YUM', 'ZBH', 'ZION']
        TRAIN_SET: &sp500_20082017_train_set ['AAP', 'ADBE', 'AFL', 'AIG', 'AIV', 'ALB', 'AMZN', 'AOS', 'APD', 'ATVI', 'BAX', 'BRK', 'C', 'CCL', 'CHD', 'CI', 'CLX', 'CMG', 'CMS', 'CNP', 'COF', 'CPB', 'CRM', 'CSCO', 'D', 'DE', 'DISH', 'EA', 'EL', 'EMR', 'EQR', 'ES', 'EXPD', 'EXR', 'FDX', 'FFIV', 'FL', 'GIS', 'GLW', 'GRMN', 'HBAN', 'HBI', 'HSIC', 'HUM', 'IDXX', 'IFF', 'INCY', 'IPG', 'IPGP', 'IT', 'ITW', 'KR', 'KSS', 'LEN', 'LMT', 'LNT', 'LRCX', 'M', 'MA', 'MAC', 'MAS', 'MCHP', 'MDLZ', 'MHK', 'MO', 'MRK', 'MSCI', 'MSFT', 'MTD', 'NDAQ', 'NRG', 'NSC', 'O', 'OKE', 'PCG', 'PKG', 'PNC', 'PPL', 'PSA', 'PVH', 'RHI', 'RJF', 'RMD', 'RRC', 'SBAC', 'SJM', 'SWKS', 'TAP', 'TSCO', 'UAA', 'UAL', 'UDR', 'ULTA', 'UNH', 'UNM', 'UNP', 'UPS', 'VTR', 'VZ', 'ZBH']
        OTHER_SETTINGS: {rand_seed: *default_seed, num_items: 10}
        OUTPUT_FILE_NAME_BASIS: "sp500_20082017"
    SP500_20082012:
        FILE_PATH:  "{DIRS.DATASET_DIR}/is_pre_data/sp500_hold_20082012_adj_close-pre.csv"
        ALL_SET: *sp500_20082017_all_set
        TRAIN_SET: *sp500_20082017_train_set
        OUTPUT_FILE_NAME_BASIS: "sp500_20082012"
    SP500_20112015:
        FILE_PATH: &sp500_20112015_file_path "{DIRS.DATASET_DIR}/is_pre_data/sp500_hold_20112015_adj_close-pre.csv"
        ALL_SET: *sp500_20082017_all_set
        TRAIN_SET: *sp500_20082017_train_set
        OUTPUT_FILE_NAME_BASIS: "sp500_20112015"
    SP500_20122017:
        FILE_PATH: "{DIRS.DATASET_DIR}/is_pre_data/sp500_hold_20122017_adj_close-pre.csv"
        ALL_SET: *sp500_20082017_all_set
        TRAIN_SET: *sp500_20082017_train_set
        OUTPUT_FILE_NAME_BASIS: "sp500_20122017"
    SP500_20112015_RAND_1:
        FILE_PATH: *sp500_20112015_file_path
        ALL_SET: *sp500_20082017_all_set
        TRAIN_SET: ['ADBE', 'AFL', 'DISH', 'FFIV', 'LMT', 'MDLZ', 'MRK', 'MSFT', 'PNC', 'PPL']
        OTHER_SETTINGS: {rand_seed: *default_seed, num_items: 10}
        OUTPUT_FILE_NAME_BASIS: "sp500_20112015_rand_1"
    SP500_20112015_RAND_2:
        FILE_PATH: *sp500_20112015_file_path
        ALL_SET: *sp500_20082017_train_set
        TRAIN_SET: ['ADBE', 'AIV', 'ALB', 'ATVI', 'CMG', 'COF', 'CRM', 'DISH', 'ES', 'EXR', 'FFIV', 'FL', 'HBI', 'IFF', 'INCY', 'IPGP', 'LEN', 'LMT', 'MA', 'MAC', 'MCHP', 'MDLZ', 'MSCI', 'OKE', 'PPL', 'PVH', 'RRC', 'UDR', 'VZ', 'ZBH']
        OTHER_SETTINGS: {rand_seed: *default_seed, num_items: 30}
        OUTPUT_FILE_NAME_BASIS: "sp500_20112015_rand_2"
    SP500_20112015_CORR_MEAN_POSITIVE_KEEP:
        FILE_PATH: *sp500_20112015_file_path
        ALL_SET: []
        TRAIN_SET: ['ADP', 'APH', 'MDT', 'PAYX']
        OUTPUT_FILE_NAME_BASIS: "sp500_20112015_corr_mean_positive_keep"
    SP500_20112015_CORR_MEAN_NEGATIVE_KEEP:
        FILE_PATH: *sp500_20112015_file_path 
        ALL_SET: *sp500_20082017_all_set
        TRAIN_SET: ['NEM', 'SCHW', 'WEC']
        OTHER_SETTINGS: {rand_seed: *default_seed}
        OUTPUT_FILE_NAME_BASIS: "sp500_20112015_corr_mean_negative_keep"
    SP500_20112015_CORR_MEAN_POSITIVE_NEGATIVE_KEEP:
        FILE_PATH: *sp500_20112015_file_path
        ALL_SET: []
        TRAIN_SET: ['ADP', 'APH', 'MDT', 'NEM', 'PAYX', 'SCHW', 'WEC']
        TRAIN_SET_SOURCE_DATASETS: ["SP500_20112015_CORR_MEAN_POSITIVE_KEEP", "SP500_20112015_CORR_MEAN_NEGATIVE_KEEP"]
        CORSS_ITEM_PAIRS: ['ADP & NEM', 'ADP & SCHW', 'ADP & WEC', 'APH & NEM', 'APH & SCHW', 'APH & WEC', 'MDT & NEM', 'MDT & SCHW', 'MDT & WEC', 'NEM & PAYX', 'PAYX & SCHW', 'PAYX & WEC']
        CORSS_ITEM_PAIRS_IDXS: [2, 4, 5, 7, 9, 10, 11, 13, 14, 15, 18, 19]
        OUTPUT_FILE_NAME_BASIS: "sp500_20112015_corr_mean_positive_negative_keep"
    SP500_20112015_PCA_CLUSTER_1:
        FILE_PATH: *sp500_20112015_file_path
        ALL_SET: *sp500_20082017_all_set
        TRAIN_SET: ['AIV', 'AMD', 'BRK', 'HBAN', 'NVDA', 'RF']
        PCA_SETTINGS: {n_samples: 389, n_featues: 1258, pca_explanation_variance_thres: 0.1, scaler: 'MinMaxScaler'}
        CLUSTER_SETTINGS: {n_samples: 389, n_features: 1, n_clusters: 35, linkage: 'complete', cluster_metric: 'euclidean', max_cluster_dist: 2.707608360527332, selected_cluter_label: 2}
        OUTPUT_FILE_NAME_BASIS: "sp500_20112015_pca_cluster_1"
    SP500_20112015_PCA_CLUSTER_2:
        FILE_PATH: *sp500_20112015_file_path
        ALL_SET: *sp500_20082017_all_set
        TRAIN_SET: ['ESS', 'IBM', 'MCK', 'ORLY']
        PCA_SETTINGS: {n_samples: 389, n_featues: 1258, pca_explanation_variance_thres: 0.1, scaler: 'MinMaxScaler'}
        CLUSTER_SETTINGS: {n_samples: 389, n_features: 1, n_clusters: 35, linkage: 'complete', cluster_metric: 'euclidean', max_cluster_dist: 2.707608360527332, selected_cluter_label: 19}
        OUTPUT_FILE_NAME_BASIS: "sp500_20112015_pca_cluster_2"
    SP500_20112015_PCA_CLUSTER_1_PCA_CLUSTER_2:
        FILE_PATH: *sp500_20112015_file_path
        ALL_SET: *sp500_20082017_all_set
        TRAIN_SET: ['AIV', 'AMD', 'BRK', 'ESS', 'HBAN', 'IBM', 'MCK', 'NVDA', 'ORLY', 'RF']
        TRAIN_SET_SOURCE_DATASETS: ["SP500_20112015_PCA_CLUSTER_1", "SP500_20112015_PCA_CLUSTER_2"]
        CORSS_ITEM_PAIRS: ['AIV & ESS', 'AIV & IBM', 'AIV & MCK', 'AIV & ORLY', 'AMD & ESS', 'AMD & IBM', 'AMD & MCK', 'AMD & ORLY', 'BRK & ESS', 'BRK & IBM', 'BRK & MCK', 'BRK & ORLY', 'ESS & HBAN', 'ESS & NVDA', 'ESS & RF', 'HBAN & IBM', 'HBAN & MCK', 'HBAN & ORLY', 'IBM & NVDA', 'IBM & RF', 'MCK & NVDA', 'MCK & RF', 'NVDA & ORLY', 'ORLY & RF']
        CORSS_ITEM_PAIRS_IDXS: [2, 4, 5, 7, 10, 12, 13, 15, 17, 19, 20, 22, 24, 27, 29, 30, 31, 33, 36, 38, 39, 41, 42, 44]
        OUTPUT_FILE_NAME_BASIS: "sp500_20112015_pca_cluster_1_pca_cluster_2"
    SP500_20112015_PCA_CLUSTER_MIX:
        FILE_PATH: *sp500_20112015_file_path
        ALL_SET: *sp500_20082017_all_set
        TRAIN_SET: ['AAP', 'AVB', 'BAC', 'CCI', 'ESS', 'MLM', 'NVDA', 'SLB', 'SRCL', 'WDC']
        PCA_SETTINGS: {n_samples: 389, n_featues: 1258, pca_explanation_variance_thres: 0.1, scaler: 'MinMaxScaler'}
        CLUSTER_SETTINGS: {n_samples: 389, n_features: 1, n_clusters: 35, linkage: 'complete', cluster_metric: 'euclidean', selected_cluter_labels: [2, 4, 5, 6, 9, 12, 15, 19, 29, 32], selected_cluter_sample: {'cluster_label_2': ['NVDA'], 'cluster_label_4': ['AAP'], 'cluster_label_5': ['MLM'], 'cluster_label_6': ['BAC'], 'cluster_label_9': ['WDC'], 'cluster_label_12': ['SRCL'], 'cluster_label_15': ['AVB'], 'cluster_label_19': ['ESS'], 'cluster_label_29': ['SLB'], 'cluster_label_32': ['CCI']}}
        OTHER_SETTINGS: {rand_seed: *default_seed, num_samples_each_cluster: 1, num_selected_clusters: 10}
        OUTPUT_FILE_NAME_BASIS: "sp500_20112015_pca_cluster_mix"
    SP500_20112015_PCA_CLUSTER_PAIRS_1:
        FILE_PATH: &sp500_20112015_corr_s1_w50_file_path  "{DIRS.PIPELINE_DATA_DIR}/sp500_20112015-train_train/pearson/corr_data/corr_s1_w50.csv"
        ALL_SET: *sp500_20082017_train_set
        TRAIN_PAIRS_SET: ['CMS & EA', 'D & EA', 'EA & ES', 'EA & LNT']
        PCA_SETTINGS: {n_samples: 4950, n_featues: 1209, pca_explanation_variance_thres: 0.01, scaler: 'MinMaxScaler'}
        CLUSTER_SETTINGS: {n_samples: 4950, n_features: 34, n_clusters: 2193, linkage: 'complete', cluster_metric: 'euclidean', max_cluster_dist: 9.90603769136474, selected_cluter_label: 714}
        OUTPUT_FILE_NAME_BASIS: "sp500_20112015_pca_cluster_pairs_1"
    SP500_20112015_PCA_CLUSTER_PAIRS_2:
        FILE_PATH: *sp500_20112015_corr_s1_w50_file_path
        ALL_SET: *sp500_20082017_train_set
        TRAIN_PAIRS_SET: ['AIV & MO', 'EQR & MO', 'EXR & MO', 'MO & UDR']
        PCA_SETTINGS: {n_samples: 4950, n_featues: 1209, pca_explanation_variance_thres: 0.01, scaler: 'MinMaxScaler'}
        CLUSTER_SETTINGS: {n_samples: 4950, n_features: 34, n_clusters: 2193, linkage: 'complete', cluster_metric: 'euclidean', max_cluster_dist: 9.90603769136474, selected_cluter_label: 1746}
        OUTPUT_FILE_NAME_BASIS: "sp500_20112015_pca_cluster_pairs_2"
    SP500_20112015_PCA_CLUSTER_PAIRS_1_PCA_CLUSTER_PAIRS_2:
        FILE_PATH: *sp500_20112015_corr_s1_w50_file_path
        ALL_SET: *sp500_20082017_train_set
        TRAIN_PAIRS_SET: ['AIV & MO', 'CMS & EA', 'D & EA', 'EA & ES', 'EA & LNT', 'EQR & MO', 'EXR & MO', 'MO & UDR']
        TRAIN_SET_SOURCE_DATASETS: ["SP500_20112015_PCA_CLUSTER_PAIRS_1", "SP500_20112015_PCA_CLUSTER_PAIRS_2"]
        OUTPUT_FILE_NAME_BASIS: "sp500_20112015_pca_cluster_pairs_1_pca_cluster_pairs_2"
    SP500_20112015_PCA_CLUSTER_PAIRS_GIVEN_PAIR:
        FILE_PATH: *sp500_20112015_corr_s1_w50_file_path
        ALL_SET: *sp500_20082017_train_set
        TRAIN_PAIRS_SET: ['APD & LMT', 'COF & EMR', 'COF & IT', 'DISH & LMT', 'LMT & MCHP']
        TRAIN_SET_SOURCE_DATASETS: ["SP500_20112015_RAND_1"]
        GIVEN_PAIRS_IDX: [3]
        PCA_SETTINGS: {n_samples: 4950, n_featues: 1209, pca_explanation_variance_thres: 0.01, scaler: 'MinMaxScaler'}
        CLUSTER_SETTINGS: {n_samples: 4950, n_features: 34, n_clusters: 2193, linkage: 'complete', cluster_metric: 'euclidean', selected_cluter_label: 31}
        OTHER_SETTINGS: {designated_sample: "DISH & LMT", designated_sample_idx: 2276}
        OUTPUT_FILE_NAME_BASIS: "sp500_20112015_pca_cluster_pairs_given_pair"
    SP500_20112015_PCA_CLUSTER_PAIRS_GIVEN_PAIR_2:
        FILE_PATH: *sp500_20112015_corr_s1_w50_file_path
        ALL_SET: *sp500_20082017_train_set
        TRAIN_PAIRS_SET: ['ADBE & MCHP', 'ADBE & RHI', 'ADBE & ZBH', 'APD & IPGP', 'MCHP & RJF']
        TRAIN_SET_SOURCE_DATASETS: ["SP500_20112015"]
        GIVEN_PAIRS_IDX: [0]
        PCA_SETTINGS: {n_samples: 4950, n_featues: 1209, pca_explanation_variance_thres: 0.01, scaler: 'MinMaxScaler'}
        CLUSTER_SETTINGS: {n_samples: 4950, n_features: 34, n_clusters: 2193, linkage: 'complete', cluster_metric: 'euclidean', selected_cluter_label: 959}
        OTHER_SETTINGS: {designated_sample: "ADBE & MCHP", designated_sample_idx: 158}
        OUTPUT_FILE_NAME_BASIS: "sp500_20112015_pca_cluster_pairs_given_pair_2"
    SP500_20112015_PCA_CLUSTER_MIX_GIVEN_ITEMS:
        FILE_PATH: *sp500_20112015_file_path
        ALL_SET: *sp500_20082017_train_set
        TRAIN_SET: ['AAP', 'ADBE', 'CRM', 'DISH', 'EMR', 'HUM', 'LMT', 'LRCX', 'TAP', 'TSCO', 'VTR']
        GIVEN_PAIRS_IDX: [29]
        TRAIN_SET_SOURCE_DATASETS: ["SP500_20112015_PCA_CLUSTER_PAIRS_GIVEN_PAIR", "SP500_20112015_RAND_1"]
        PCA_SETTINGS: {n_samples:100 , n_featues:1258, pca_explanation_variance_thres: 0.1, scaler: 'MinMaxScaler'}
        CLUSTER_SETTINGS: {n_samples: 100, n_features: 1, n_clusters: 19, linkage: 'complete', cluster_metric: 'euclidean', selected_cluter_labels: [1, 3], selected_cluter_sample: {'cluster_label_1': ['ADBE', 'CRM', 'DISH', 'EMR', 'LRCX', 'TAP', 'TSCO', 'VTR'], 'cluster_label_3': ['AAP', 'HUM', 'LMT']}}
        OTHER_SETTINGS: {rand_seed: *default_seed, designated_samples: ["DISH", "LMT"]}
        OUTPUT_FILE_NAME_BASIS: "sp500_20112015_pca_cluster_mix_given_items"
    SP500_20112015_PCA_CLUSTER_MIX_GIVEN_ITEMS_2:
        FILE_PATH: *sp500_20112015_file_path
        ALL_SET: *sp500_20082017_train_set
        TRAIN_SET: ['ADBE', 'AMZN', 'AOS', 'ATVI', 'CNP', 'CRM', 'CSCO', 'DISH', 'EMR', 'GLW', 'KR', 'LRCX', 'MAS', 'MCHP', 'TAP', 'TSCO', 'VTR']
        GIVEN_PAIRS_IDX: [12]
        TRAIN_SET_SOURCE_DATASETS: ["SP500_20112015_PCA_CLUSTER_PAIRS_GIVEN_PAIR_2", "SP500_20112015"]
        PCA_SETTINGS: {n_samples:100 , n_featues:1258, pca_explanation_variance_thres: 0.1, scaler: 'MinMaxScaler'}
        CLUSTER_SETTINGS: {n_samples: 100, n_features: 1, n_clusters: 19, linkage: 'complete', cluster_metric: 'euclidean', selected_cluter_labels: [1, 9], selected_cluter_sample: {'cluster_label_1': ['ADBE', 'CRM', 'DISH', 'EMR', 'LRCX', 'TAP', 'TSCO', 'VTR'], 'cluster_label_9': ['AMZN', 'AOS', 'ATVI', 'CNP', 'CSCO', 'GLW', 'KR', 'MAS', 'MCHP']}}
        OTHER_SETTINGS: {rand_seed: *default_seed, designated_samples: ['ADBE', 'MCHP']}
        OUTPUT_FILE_NAME_BASIS: "sp500_20112015_pca_cluster_mix_given_items_2"
